### ISSUE TITLE
Admin 0 - Finalize milestones #1

### ISSUE THREAD

**Issue by steve0xp** [Dev-Rel-as-a-Service/SpeedRunLUKSO#1]
# TODO:

Tanto:
- [x] Submit the milestones into the portal tonight. Please lmk when that is done 🙂
- [ ] Check that I can access the application, if I cannot (which it seems I can’t on my end), then please see what you can do to fix this. Maybe you just need to ask Clara what’s going on and make sure they have my right email: stevep0xp@gmail.com
- [ ] Send Steve any LUKSO specific stuff that will help Steve onboard quickly for the grant requirements.

Steve:
- [x] Create a forked repo of SRE to start with for SRL
- [x] Outline the initial github project board
- [ ] Read up on LUKSO specific work as needed
