### ISSUE TITLE
Milestone 1 - Smart Contracts (LSPs)

### ISSUE THREAD

**Issue by steve0xp** [Dev-Rel-as-a-Service/SpeedRunLUKSO#10]
# Goal

Figure out what LSPs to focus on first, and if there are already similar LSP tutorials available that we can simply point to for students. It is good to work smarter, not harder!

## TODOs

Steve:
- [ ] Reach out to LUKSO stakeholders to understand if this has been done at all yet. Document responses within this issue.
- [ ] Draft scope of LSP coverage within milestone 1 challenges
- [ ] Seek feedback from LUKSO community (grants committee and others) on LSP coverage scope.
- [ ] Likely outline LSP coverage for Milestones 2 too

**Comment by steve0xp** [comment]
# Possible Ways to Showcase LSPs in this Grant

## LSP 8 - Challenge 0 

### Milestone 1 Related:
- [ ] Incorporate LSP8 (even if it's just empty template functions adhering to their standard)
- [ ] Could add in details for each respective new feature of LSP8

### Milestone 2 Related:
- [ ] Create functioning scripts to carry out interactions showcasing the unique functionality of LSP8 (hooks, evolution of nfts, etc. if needed / of interest).
^^ the above is only of interest if it hasn't been done and can easily be pointed to already in the LUKSO ecosystem.

## LSP 7 - Challenge 2

### Milestone 1 Related:
- [ ] Use LSP7, but just with basic or even empty details for LUKSO extra functionalities.
   - This is dependent on if it's scope creep based on amount of work, and if it has been done by another pre-existing LUKSO resource.

### Milestone 2 Related:
- [ ] Add more to the challenge that is LUKSO specific
