### ISSUE TITLE
Milestone 1: Create a SpeedRunLUKSO that is a Fork of SRE (First Three Challenges Only) Working w/ LUKSO and Relevant Standards

### ISSUE THREAD

**Issue by steve0xp** [Dev-Rel-as-a-Service/SpeedRunLUKSO#4]
# TODO

Both:
- [x] Create forked repo, remove unnecessary challenges
- [ ] Outline requirements for each challenge

Tanto:
- [ ] Implement the front end side of the challenge

Steve:
- [ ] Implement smart contracts side of the challenge
- [ ] Add unit test adjustments as needed

**Comment by tantodefi** [comment]
Started on changes for challenge 0&1 with #7 and #8 and #9

TODO's

Tanto
- [ ] edit the submission instructions in /challenge-0-simple-nft-example/readme.md L17 and L32 /app/page.tsx
- [ ] edit the challenge 0 NFT picture
- [ ] add CG link to support in footer.tsx
- [ ] update image in readme L125
- [ ] edit sidequest in readme L141
- [ ] update bg colour
- [ ] retake/replace final screenshots of frontend 

Steve:
(on branch 'challenge-0-simple-nft')
- [ ] readme L151 change YourCollectible.sol to YourLSP8Collectible.sol
- [ ] readme L193-205 blockscout API keys for LUKSO ?[ testnet explorer](https://explorer.execution.testnet.lukso.network/)
- [ ] change branch name to 'challenge-0-simple-nft-with-lsp8'

Both:
- [ ] readme UPAGE + UCLOUD section

**Comment by steve0xp** [comment]
Steve - this week:
- [ ] Review LSPs relevant to copies of SRE challenges for SRLUKSO
- [ ] Make implementation changes to the challenges and troubleshoot. Starting with challenge 0 and challenge 1.
